env:
  es2021: true
  jest: true
  node: true
extends:
  - "plugin:import/typescript"
  - "plugin:jest/recommended"
ignorePatterns:
  - "*.js"
  - "*.d.ts"
  - node_modules/
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  project: ./tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
  - jest
root: true
rules:
  "@typescript-eslint/adjacent-overload-signatures":
    - error
  "@typescript-eslint/array-type":
    - error
    - default: array-simple
  "@typescript-eslint/await-thenable":
    - error
  "@typescript-eslint/consistent-type-definitions":
    - error
    - interface
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
  "@typescript-eslint/explicit-member-accessibility":
    - error
    - accessibility: explicit
      overrides:
        constructors: no-public
  "@typescript-eslint/member-delimiter-style":
    - error
  "@typescript-eslint/method-signature-style":
    - error
    - method
  "@typescript-eslint/no-require-imports":
    - error
  "@typescript-eslint/no-unused-vars":
    - error
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing:
    - error
    - never
  array-element-newline:
    - error
    - consistent
  arrow-body-style:
    - error
    - always
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
    - after: true
      before: true
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: false
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  curly:
    - error
    - all
  eol-last:
    - error
    - always
  func-call-spacing:
    - error
    - never
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline:
    - error
    - multiline
  generator-star-spacing:
    - error
    - after: false
      before: true
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "**/build-tools/**"
        - "**/test/**"
      optionalDependencies: false
      peerDependencies: false
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator: first
  key-spacing:
    - error
    - afterColon: true
      beforeColon: false
      mode: strict
  keyword-spacing:
    - error
  linebreak-style:
    - error
    - unix
  lines-between-class-members:
    - error
    - always
  max-len:
    - error
    - code: 120
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreUrls: true
  max-statements-per-line:
    - error
    - max: 1
  multiline-comment-style:
    - error
    - separate-lines
  new-cap:
    - error
  new-parens:
    - error
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 1
  no-array-constructor:
    - error
  no-await-in-loop:
    - error
  no-bitwise:
    - error
    - int32Hint: true
  no-confusing-arrow:
    - error
  no-duplicate-imports:
    - error
  no-lonely-if:
    - error
  no-loss-of-precision:
    - error
  no-mixed-operators:
    - error
  no-multi-assign:
    - error
  no-multi-spaces:
    - error
    - ignoreEOLComments: true
  no-multiple-empty-lines:
    - error
    - max: 2
      maxBOF: 0
      maxEOF: 0
  no-nested-ternary:
    - error
  no-new-object:
    - error
  no-promise-executor-return:
    - error
  no-tabs:
    - error
  no-template-curly-in-string:
    - error
  no-trailing-spaces:
    - error
  no-unneeded-ternary:
    - error
  no-whitespace-before-property:
    - error
  object-curly-newline:
    - error
    - consistent: true
      multiline: true
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  one-var-declaration-per-line:
    - error
    - always
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - before
  prefer-arrow-callback:
    - error
  prefer-exponentiation-operator:
    - error
  prefer-rest-params:
    - error
  prefer-template:
    - error
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true
  semi:
    - error
    - always
  semi-spacing:
    - error
    - after: true
      before: false
  semi-style:
    - error
    - last
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: never
      asyncArrow: always
      named: never
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
    - int32Hint: true
  space-unary-ops:
    - error
  spaced-comment:
    - error
    - always
    - block:
        exceptions:
          - "*"
      line:
        exceptions:
          - /
  switch-colon-spacing:
    - error
    - after: true
      before: false
  template-curly-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never
  yield-star-spacing:
    - error
    - after: false
      before: true
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx
  import/resolver:
    node: {}
    typescript:
      directory: ./tsconfig.json
